hwc_session: move a break
As written, this loop only runs once, which makes clang's new warning
unhappy:

hardware/qcom-caf/sm8250/display/composer/hwc_session.cpp:828:51: error: loop will run at most once (loop increment never executed) [-Werror,-Wunreachable-code-loop-increment]
  for (size_t i = 0; i < pending_refresh_.size(); i++) {
                                                  ^~~

Chatting with qcom, this appears to be a bug, and the best fix is to
move the `break` into the `if`.

Bug: 150166387
Test: TreeHugger
Change-Id: Icb64eed5b894b9188f5265094587dd802207ba66